// <auto-generated />
using System;
using BitirmeProj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitirmeProj.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20231212112056_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BitirmeProj.Models.Application", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdvertID")
                        .HasColumnType("int");

                    b.Property<int?>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PersonID");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("BitirmeProj.Models.CV", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("longtext");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("CV");
                });

            modelBuilder.Entity("BitirmeProj.Models.Job", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Active")
                        .HasColumnType("int");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("JobLocation")
                        .HasColumnType("longtext");

                    b.Property<int?>("JobType")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("Questions")
                        .HasColumnType("longtext");

                    b.Property<string>("Salary")
                        .HasColumnType("longtext");

                    b.Property<string>("Skills")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("PersonID");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("BitirmeProj.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("BitirmeProj.Models.Application", b =>
                {
                    b.HasOne("BitirmeProj.Models.Person", null)
                        .WithMany("Applications")
                        .HasForeignKey("PersonID");
                });

            modelBuilder.Entity("BitirmeProj.Models.CV", b =>
                {
                    b.HasOne("BitirmeProj.Models.Person", null)
                        .WithOne("CV")
                        .HasForeignKey("BitirmeProj.Models.CV", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BitirmeProj.Models.Job", b =>
                {
                    b.HasOne("BitirmeProj.Models.Person", "Applications")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applications");
                });

            modelBuilder.Entity("BitirmeProj.Models.Person", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CV");
                });
#pragma warning restore 612, 618
        }
    }
}
